version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Ping another pipeline
          command: |
            curl --request POST \
              --url https://circleci.com/api/v2/project/gh/murillowelsi/cypress-e2e/pipeline \
              --header "Circle-Token: 5ad0780c7d15885b6889aaa841a96848883b4378" \
              --header "content-type: application/json" \
              --data '{"branch":"main"}'
  say-bye:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Bye"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello
