version: 2.1

jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Trigger the Build Job
          command: |
            printf "Triggering an $PROJECT build on the main branch\n\n"

            BUILD_INFO=$(curl -X POST -H -d \
                "https://circleci.com/api/v1/project/github/murillowelsi/cypress-e2e/tree/main?circle-token=5ad0780c7d15885b6889aaa841a96848883b4378")

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/github/murillowelsi/cypress-e2e/tree/main"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
