name: Build Artifacts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: murillowelsi
        repo: cypress-e2e
        github_token: ${{ secrets.TOKEN }}
        workflow_file_name: cypress-run.yml