name: Build Artifacts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.0
      with:
        owner: murillowelsi
        repo: cypress-e2e
        github_token: ${{ secrets.TOKEN }}
        github_user: murillowelsi
        workflow_file_name: main.yml
        ref: main
        wait_interval: 10
        client_payload: '{}'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true
        last_workflow_interval: 1